# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LrqYID6EQli67uYm8eF27LoP4_ZVSha
"""

f = open('/content/input1.txt', 'r')
num = 50
zero_counter = 0 # part 1
zero_click_counter = 0 # part 2
for i in f:
  currently_zero = num == 0
  forward = True
  if (i[:1] == 'L'):
    forward = False
  else:
  amount = int(i[1:])
  if (forward):
    num += amount
    if (num > 99):
      zero_click_counter += num // 100
  else:
    num -= amount
    if (num <= 0):
      zero_click_counter += abs(num // 100)
      if (num % 100 == 0):
        zero_click_counter += 1
      if (currently_zero):
        zero_click_counter -= 1
  num %= 100
  if num == 0:
    zero_counter += 1
print(zero_counter) # part 1 answer
print(zero_click_counter) # part 2 answer