# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrxXCkmk-FeFjPHN_jLCav6BeRHeClrT
"""

def recursive_add_string_p1(invalidset, currval, strlen, first=False):
  startnum = 0
  if (first):
    startnum = 1
  for i in range(startnum, 10):
    newval = currval + str(i)
    if strlen > len(newval):
      recursive_add_string_p1(invalidset, newval, strlen)
    else:
      invalidset.add(int(newval + newval))

def recursive_add_string_p2(invalidset, currval, maxlen, first=False):
  startnum = 0
  if (first):
    startnum = 1
  for i in range(startnum, 10):
    newval = currval + str(i)
    val_to_add = newval
    while len(val_to_add) + len(newval) <= maxlen:
      val_to_add += newval
      invalidset.add(int(val_to_add))

    if maxlen // 2 > len(newval):
      recursive_add_string_p2(invalidset, newval, maxlen)


f = open('input2.txt', 'r')
data = []
invalidset_p1 = set()
invalidset_p2 = set() # use a set so invalid numbers won't be repeated
result_p1 = 0  # part 1
result_p2 = 0  # part 2
max_string_length = 0

for i in f:
  data = i.split(',')
for i in data:
  minmax = i.split('-')
  max = minmax[1]
  if len(max) > max_string_length:
    max_string_length = len(max)

for i in range(1, max_string_length // 2 + 1):
  recursive_add_string_p1(invalidset_p1, '', i, True)

recursive_add_string_p2(invalidset_p2, '', max_string_length, True)

for i in data:
  minmax = i.split('-')
  min = int(minmax[0])
  max = int(minmax[1])
  vallist1 = [item for item in invalidset_p1 if min < item < max]
  for val in vallist1:
    result_p1 += val

  vallist2 = [item for item in invalidset_p2 if min < item < max]
  for val in vallist2:
    result_p2 += val

print(result_p1) # part 1 answer
print(result_p2) # part 2 answer