# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTbzyR97pgzBymFMtX48vGF9ZMysIf0q
"""

# part 1
f = open("input3.txt", "r")
data = []
result = 0
for i in f:
  data.append(i.strip());

for i in data:
  mapcounter = {}
  for j in i:
    if int(j) not in mapcounter:
      mapcounter[int(j)] = 1
    else :
      mapcounter[int(j)] += 1

  keys = list(mapcounter.keys())
  keys.sort()
  maxkey = keys[-1]
  if mapcounter[maxkey] >= 2:
    # print(int(str(maxkey) + str(maxkey)))
    result += int(str(maxkey) + str(maxkey))
  else:
    topvalindex = i.index(str(maxkey));
    restoflist = i[topvalindex+1:]
    if len(restoflist) == 0:
      maxkeysecond = keys[-2]
      result += int(str(maxkeysecond) + str(maxkey))
    else:
      secondmaxval = max(restoflist)
      result += int(str(maxkey) + str(secondmaxval))
print(result) # part 1 result

# part 2
result = 0
for i in data:
  digitsleft = 12
  checkingdata = i[:-digitsleft+1]
  cellvoltage = ''
  previousmaxindex = 0

  while len(checkingdata) > 1 and digitsleft != 0:
    digitsleft -= 1
    maxdigit = max(checkingdata)
    cellvoltage += maxdigit
    maxdigitindex = checkingdata.index(maxdigit)
    if digitsleft <= 1:
      checkingdata = i[previousmaxindex + maxdigitindex + 1 :]
    else:
      checkingdata = i[previousmaxindex + maxdigitindex + 1 : -digitsleft + 1]
    previousmaxindex += maxdigitindex + 1
  if digitsleft > 0:
    cellvoltage += i[-digitsleft:]
  result += int(cellvoltage)

print(result) # part 2 result

