# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5KLhq1xXXxnfgX07Fd9teP19DJDoLWl
"""

f = open("input4.txt", "r")

def find_adjacent(grid, x, y, maxx, maxy):
  adjacent = 0
  currx = x - 1
  curry = y - 1
  for i in range(currx, currx + 3):
    if i < 0 or i >= maxx:
      continue
    for j in range(curry, curry + 3):
      if j < 0 or j >= maxy:
        continue
      if i == x and j == y:
        continue
      if grid[i][j] == '@':
        adjacent += 1
  return adjacent

grid = []
maxrows = 0
maxcols = 0
result = 0
result2 = 0

for i in f:
  row = list(i.strip())
  grid.append(row)

maxrows = len(grid)
maxcols = len(grid[0])

# part 1 solution
for i in range(0, maxrows):
  for j in range(0, maxcols):
    if grid[i][j] == '@':
      if find_adjacent(grid, i, j, maxrows, maxcols) < 4:
        result += 1

# part 2 solution
currentremoved = -1
while currentremoved != 0:
  currentremoved = 0
  for i in range(0, maxrows):
    for j in range(0, maxcols):
      if grid[i][j] == '@':
        if find_adjacent(grid, i, j, maxrows, maxcols) < 4:
          currentremoved += 1
          result2 += 1
          grid[i][j] = '.'

print(result) # part 1 result
print(result2) # part 2 result