# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhBmGVg6Xn1uH_34H4ALTJ3RwJdNrrMr
"""

f = open("input5.txt", "r")

freshmap = {}
valstocheck = []

for i in f:
  i = i.strip()
  if '-' in i:
    bounds = i.split('-')
    if int(bounds[0]) not in freshmap:
      freshmap[int(bounds[0])] = int(bounds[1])
    else:
      if freshmap[int(bounds[0])] < int(bounds[1]):
        freshmap[int(bounds[0])] = int(bounds[1])
  elif i.strip() == "":
    continue
  else:
    valstocheck.append(int(i))

# sorting all the keys makes both solutions significantly easier
sortedminkeys = sorted(list(freshmap.keys()))

# part 1 solve
result = 0
for i in valstocheck:
  checklist = [item for item in sortedminkeys if i >= item]
  for j in checklist:
    if j <= i <= freshmap[j]:
      result += 1
      break

# part 2 solve
result2 = 0
# use bounds to see what we have and haven't calculated
minbound = -1
maxbound = -1
for i in sortedminkeys:
  min = i
  max = freshmap[i]
  if min > maxbound:
    # set new bounds
    minbound = min
    maxbound = max
    result2 += max - min + 1
  elif min >= minbound and max <= maxbound:
    # all values are already within bounds
    continue
  elif min >= minbound and min <= maxbound and max > maxbound:
    # min is within bound, but max is beyond bound
    result2 += max - maxbound
    maxbound = max
  else:
    # this should never be triggered
    print("unhandled edge case")


print(result) # part 1 result
print(result2) # part 2 result