# -*- coding: utf-8 -*-
"""day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmiOy5l2U6GsGhLQF36RL_dHUwb5pkWO
"""

f = open("input6.txt", "r")

grid = [] # cleaned data for part 1
grid2 = [] # cleaned data for part 2
for i in f:
  line = i.split()
  grid.append(line)

  # gotta use replace and not strip as strip will remove whitespace
  line2 = list(i.replace('\n', ''))
  grid2.append(line2)

# part 1
result = 0
for i in range(0, len(grid[0])):
  valtoadd = 0
  operator = grid[-1][i] # get operator

  # add or multiply the rest of the numbers together
  for j in range(0, len(grid) - 1):
    if operator == '+':
      valtoadd += int(grid[j][i])
    elif operator == '*':
      if valtoadd > 0:
        valtoadd *= int(grid[j][i])
      else:
        valtoadd = int(grid[j][i])
    else:
      print("This should never occur")
  result += valtoadd

# part 2
result2 = 0
valstomath = [] # list of nums to add/multiply together
for i in range(len(grid2[0])-1, -1, -1):
  # find vertical value and add it to the list
  val = ''
  for j in range(0, len(grid2)-1):
    val += grid2[j][i].strip()
  if len(val) > 0:
    valstomath.append(val)

  # if there's an operator, perform it on the list of vals
  operator = grid2[-1][i].strip()
  if len(operator) > 0:
    valtoadd = 0
    if operator == '+':
      for j in valstomath:
        valtoadd += int(j)
    elif operator == '*':
      for j in valstomath:
        if valtoadd == 0:
          valtoadd = int(j)
        else:
          valtoadd *= int(j)
    else:
      print("This should never occur")

    valstomath = [] # reset the list of nums

    result2 += valtoadd


print(result) # part 1 result
print(result2) # part 2 result