# -*- coding: utf-8 -*-
"""day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOYogRdRXfZLXZ8w-cAfllYuSQNqzxPX
"""

f = open("input7.txt", "r")

# part 1 solution
def traverse_beam_down(grid, x, y):
  # recursive solution: Add beams to the grid. Count the amount of splits
  while x < len(grid):
    item = grid[x][y]
    if item == '.':
      grid[x][y] = "|"
    elif item == '|':
      return 0
    elif item == '^':
      splitamount = 1
      if grid[x][y-1] == '.':
        grid[x][y-1] = '|'
        splitamount += traverse_beam_down(grid, x+1, y-1)
      if grid[x][y+1] == '.':
        grid[x][y+1] = '|'
        splitamount += traverse_beam_down(grid, x+1, y+1)
      return splitamount
    else:
      print("This should never occur")
    x += 1
  return 0

# part 2 solution
def reformat_quantum_grid(grid, x):
  # Use the beams from part 1 to calc the number of universes/
  # Starts from the bottom and combines the universes until you reach a single
  # digit

  # convert beams into numbers
  for i in range(0, len(grid[x])):
    if grid[-1][i] == '|':
      grid[-1][i] = 1
  startindex = -1
  while x >= 0:
    # add the same number into the above line
    for i in range(0, len(grid[x])):
      item = grid[x][i]
      if item == 'S':
        startindex = i
        break
      if item == '|':
        print("This should already be done")
      elif isinstance(item, int):
        if grid[x-1][i] == '|':
          grid[x-1][i] = item

    # now check for splitters
    for i in range(0, len(grid[x])):
      item = grid[x][i]
      # if there's a splitter, combine the universes from the left and right
      if item == '^' and grid[x-1][i] == '|':
        universes = int(grid[x][i-1]) + int(grid[x][i+1])
        grid[x-1][i] = universes
    x -= 1
  return grid[1][startindex]


grid = []
result = 0
result2 = 0
for i in f:
  grid.append(list(i.strip()))

startindex = grid[0].index('S')

result = traverse_beam_down(grid, 1, startindex)

result2 = reformat_quantum_grid(grid, len(grid)-1)

print(result) # part 1 result
print(result2) # part 2 result

